# Generated by Django 4.0.3 on 2022-03-13 02:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('roomManagementSystem', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rooms',
            old_name='room_name',
            new_name='hotel_name',
        ),
        migrations.AddField(
            model_name='rooms',
            name='room_price',
            field=models.FloatField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
