# Generated by Django 4.0.3 on 2022-04-03 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roomManagementSystem', '0004_alter_rooms_room_desc_alter_rooms_room_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rooms',
            name='room_type',
            field=models.CharField(choices=[('1', 'Single'), ('2', 'Double')], max_length=30),
        ),
    ]
