# Generated by Django 4.0.3 on 2022-04-07 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roomManagementSystem', '0007_rooms_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='rooms',
            name='end_date',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='rooms',
            name='start_date',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='rooms',
            name='room_number',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
