# Generated by Django 4.0.3 on 2022-04-10 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roomManagementSystem', '0010_photogallary_rooms'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photogallary',
            old_name='multipleimages',
            new_name='room_image',
        ),
        migrations.RemoveField(
            model_name='rooms',
            name='room_image',
        ),
    ]
