# Generated by Django 4.0.3 on 2022-04-10 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roomManagementSystem', '0011_rename_multipleimages_photogallary_room_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rooms',
            name='cover_image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
