# Generated by Django 4.0.3 on 2022-04-20 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roomManagementSystem', '0018_remove_reserveddetails_payement_completed_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookeddetails',
            old_name='payement_completed',
            new_name='payement_status',
        ),
        migrations.AddField(
            model_name='reserveddetails',
            name='payement_status',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
