# Generated by Django 4.0.3 on 2022-04-20 19:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roomManagementSystem', '0019_rename_payement_completed_bookeddetails_payement_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookeddetails',
            name='check_in',
        ),
        migrations.RemoveField(
            model_name='bookeddetails',
            name='check_out',
        ),
        migrations.RemoveField(
            model_name='bookeddetails',
            name='payement_status',
        ),
        migrations.RemoveField(
            model_name='bookeddetails',
            name='total_price',
        ),
        migrations.AddField(
            model_name='bookeddetails',
            name='booked',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='roomManagementSystem.reserveddetails'),
        ),
    ]
