# Generated by Django 4.0.3 on 2022-04-02 08:51

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserManagementSystem', '0002_customers_hotelowner_user_is_customer_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customers',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='customers',
            name='is_customer',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='customers',
            name='is_hotelOwner',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_customer',
            field=models.BooleanField(default=True),
        ),
    ]
