# Generated by Django 4.0.3 on 2022-04-02 09:26

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserManagementSystem', '0003_alter_customers_managers_customers_is_customer_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='hotelowner',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='hotelowner',
            name='is_customer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hotelowner',
            name='is_hotelOwner',
            field=models.BooleanField(default=True),
        ),
        migrations.DeleteModel(
            name='customers',
        ),
    ]
