# Generated by Django 4.0.3 on 2022-04-02 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserManagementSystem', '0004_alter_hotelowner_managers_hotelowner_is_customer_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='hotelowner',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='hotelowner',
            name='is_customer',
        ),
        migrations.RemoveField(
            model_name='hotelowner',
            name='is_hotelOwner',
        ),
    ]
