# Generated by Django 4.0.3 on 2022-04-02 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserManagementSystem', '0005_alter_hotelowner_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelowner',
            name='email',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='hotelowner',
            name='first_name',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='hotelowner',
            name='last_name',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='hotelowner',
            name='password1',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='hotelowner',
            name='password2',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='hotelowner',
            name='username',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='hotelowner',
            name='hotel_name',
            field=models.CharField(default='', max_length=20),
        ),
    ]
