# Generated by Django 4.0.3 on 2022-04-02 11:17

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserManagementSystem', '0007_rename_password1_hotelowner_password_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='hotelowner',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='hotelowner',
            name='email',
        ),
        migrations.RemoveField(
            model_name='hotelowner',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='hotelowner',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='hotelowner',
            name='password',
        ),
        migrations.RemoveField(
            model_name='hotelowner',
            name='username',
        ),
    ]
