# Generated by Django 4.0.3 on 2022-04-03 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserManagementSystem', '0008_alter_hotelowner_managers_remove_hotelowner_email_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='hotelowner',
            managers=[
            ],
        ),
        migrations.AddField(
            model_name='hotelowner',
            name='is_customer',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='hotelowner',
            name='is_hotelOwner',
            field=models.BooleanField(default=True),
        ),
    ]
